### ISSUE TITLE
Review offline experience

### ISSUE THREAD

**Issue by ghost** [manifoldjs/ManifoldCordova#30]
This concern was raised in #23:

Currently, an offline overlay is automatically displayed when the connection is lost. However, there are scenarios when the page was properly loaded, and the user wants to continue seeing the content of the page even if the device is eventually disconnected.

The behavior should be reviewed so that:
- When the connection is lost, let the user keep seeing the app's content and do not show the offline overlay
- If the user performs an action that requires Internet connection and there is no connection, show the offline overlay
- When the connection is restored, hide the offline overlay

We should look at the Cordova's _ErrorUrl_ preference which might cover this scenario.

**Comment by boyofgreen** [comment]
I'd like to look at this one and see if we can improve this scenario.

**Comment by 3rand** [comment]
Any hints on how to make the offlineWebView support plugin calls? It seems that as of now its a simple webview that shows and hides.
It would solve so many nice scenarios if both webviews were cordova-enabled. This way you could have extended functionality in the offline page, for instance communicating with a plugin to serve local content e.g. a mp3 file already downloaded while online previously.

**Comment by DaveVoyles** [comment]
So you are suggesting something like store the data locally using indexedDB or local cache until the user gets online again, at that point give them the ability to connect to their remote content again?

**Comment by 3rand** [comment]
I'm suggesting something something fairly less specific:
Say you have 2 html-apps 1 online and 1 'offline' in the app bundle. 
If you switch to the offline app because connectivity loss, or even on request from the user, that app loads in a plain webview. Im suggesting to have that webview be a cordovawebview so the offline app could replicate calls to plugins just like the online app does.

Perhaps there's something wrong with my approach, but i see this as a way to serve not just a html page on the offline view but a whole app, then having it seamlessly switch to the online page where you left off.

Thanks for your feedback
