### ISSUE TITLE
Is it possible to disable offline page completely (in the manifold for example)?

### ISSUE THREAD

**Issue by gabn88** [manifoldjs/ManifoldCordova#61]
I'm aware of hostedwebapp.disableOfflinePage(), but that only loads after deviceready has fired and I'm afraid that if a device is offline it will go to the offline page, before that this function is called.

**Comment by boyofgreen** [comment]
Sure, what is the expected behavior if your offline, would you want them to get an error or are you having other content you pointing to?

**Comment by gabn88** [comment]
The default cordova behaviour is to keep the page the same, and only show an error after a link is clicked (then it finds out that the internet connection is lost and then it ends/kills the application with this error).

I would like to keep the page the same (so no offline page or whatsever, maybe a small 

```
<div>Offline</div> 
```

on the page) and when a user clicks a link that it shows an alert('No connection!') and stays on the same page. This is ideal. But the cordova default is already better for my application then the offline page.

**Comment by gabn88** [comment]
I don't want to push, but do you think this would be possible? I have no experience with writing java , but it doesn't seem to hard (I'm looking at the Android code, as I'm only targetting Android anyway).

Just the option to disable it would be enough for me.

**Comment by boyofgreen** [comment]
Hi @gabn88  let me talk to the guys who focus on android, we should be able to make an easy way to go back

**Comment by mattwoberts** [comment]
+1 for this.

I'm having problems getting the offline page to work in ios (https://github.com/manifoldjs/ManifoldCordova/issues/59)

However, using cordova-network-information via the javascript api DOES work fine.. So I can use that to handle the device going off/on-line. BUT - I need to disable the manifold offline page in entirety to get this to work.

Thanks

Matt

**Comment by vjrantal** [comment]
I also had a case where I wanted to disable the offline feature and also get rid of the extra WebViews that are created for it. I created https://github.com/manifoldjs/ManifoldCordova/pull/68 as a draft about an option how it could be made optional.

@boyofgreen: I have a feeling that it is somewhat a "no-brainer" to allow optionally getting rid of the offline feature, but probably the biggest discussion point is should it be opt-in or opt-out. In my initial PR above, I changed the feature opt-in, because I feel that it is a ManifoldJS-specific thing that might come as a "surprise" for a regular Web developer unless explicitly turned on.

I am happy to amend my commit based on the discussion and feedback, but just wanted to throw it out there to get a feeling what others think about this.
