### ISSUE TITLE
[question] Why is the injection done only when web view finishes loading?

### ISSUE THREAD

**Issue by noynir** [manifoldjs/ManifoldCordova#75]
Hi,
I have been testing your plugin, and i was wondering why is the cordova js object only available to me on window load?
window.load is too late for me :-(
Is there any special reason that your waiting for the web view finish load event to inject scripts?
Can they be injected earlier?

**Comment by pauloya** [comment]
We're having problems with this, some of the 3rd party scripts on the website can take a while to load, and this is delaying the "load" event which delays the "deviceReady" and therefore delays the whole page from rendering.
I think the best solution would be to allow the page JS to trigger the loading of the cordova scripts injection.

**Comment by boyofgreen** [comment]
Hey Pauloya,  the problem we run into is with the calling of script injection before the plugins finish loading can be problematic.   Are you loading the scripts from the package or the server?

**Comment by pauloya** [comment]
Hi, we have plugin mode: client. For me this is THE magic of this plugin! 
Server side loading of cordova scripts is something I could do without needing a plugin.

I guess my proposal of triggering things from JS won't work, because the native-webcontroller bridge needs to be built from native side and JS can't communicate with native until the bridge is there.

I can see your problem of needing to wait for all plugins to be ready on the native side, is there an event available signaling all plugins are ready? And if all you do is wait for webview.DidFinishLoad event, how can you guarantee plugins will be ready by then?

**Comment by lesteenman** [comment]
Any update on this? A way to detect when plugins are loaded would still be very useful.
